name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSYS2 (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-cmake

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build for ${{ matrix.os }}
        run: |
          python3 tools/ci-build.py

      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: eXcelSystem_${{ matrix.os }}
          path: target/